#! /bin/bash
#===============================
#
# lib
#
# 2022/02/03 Kuninori Morimoto <kuninori.morimoto.gx@renesas.com>
#===============================
download() {
	local lore="https://lore.kernel.org"
	local url=${lore}/$1
	local dir=$2
	local prefix=${3:0}
	local tmp=/tmp/linux-ml-$$
	local page=0
	local newline=0
	local num=0

	#
	# load ID list first
	#
	mkdir -p ${tmp}
	echo "${url}"
	while :
	do
		wget -q "${url}&o=${page}" -O ${tmp}/index-${page}
		grep "^href=" ${tmp}/index-${page} | grep "</a></b>$" > ${tmp}/tmp
		[ $? != 0 ] && break
		page=`expr ${page} + 200`

		cat ${tmp}/tmp | sed -e "s/^href=\"//" | sed -e "s/\/.*//" >> ${tmp}/idlist
	done

	if [ ! -f ${tmp}/idlist ]; then
		rm -fr ${tmp}
		return
	fi

	#
	# download Linux ML
	#
	for id in `cat ${tmp}/idlist`
	do
		n=`printf "%05d" ${num}`
		echo -n "."
		wget -q "${lore}/all/${id}/raw" -O ${dir}/${prefix}${n}

		newline=`expr ${newline} + 1`
		num=`expr ${num} + 1`

		if [ ${newline} = 100 ]; then
			newline=0
			echo
		fi
	done

	[ ${newline} != 80 ]; echo

	rm -fr ${tmp}
}

daily_outdir() {
	local dir=`readlink -f $1`
	mkdir -p ${dir}

	echo "${dir}"
}

daily_dayfrom() {
	local cfg=$1
	local day_from=$2
	[ x = x${day_from} ] && day_from=`cat ${cfg}`

	echo "${day_from}"
}

daily_dayto() {
	local day_to=$1
	[ x = x${day_to} ] && day_to=`date +%Y-%m-%d`

	echo "${day_to}"
}

daily_download() {
	local url=$1
	local dir=$2
	local day_from=$3
	local day_to=$4

	# This script downloads Linux ML daily
	# except ${to}. Otherwise the script will be
	# very complex if it calls many times in same day.
	local day=${day_from}
	while [ x${day} != x${day_to} ]
	do
		local prefix=`echo ${day} | sed -e "s/-//g"`
		download "all/?q=tc%3A%28${url}%29+AND+d%3A${day}..${day}" ${dir} ${prefix}

		day=`date '+%Y-%m-%d' --date "1 day ${day}"`
	done
}
