#! /bin/bash
#===============================
#
# lib
#
# 2022/02/03 Kuninori Morimoto <kuninori.morimoto.gx@renesas.com>
#===============================
download() {
	local lore="https://lore.kernel.org"
	local url=${lore}/$1
	local dir=$2
	local prefix=${3:0}
	local tmp=/tmp/linux-ml-$$
	local page=0
	local newline=0
	local num=0

	#
	# load ID list first
	#
	mkdir -p ${tmp}
	while :
	do
		echo "${url}&o=${page}"
		wget -q "${url}&o=${page}" -O ${tmp}/index-${page}
		grep "^href=" ${tmp}/index-${page} | grep "</a></b>$" > ${tmp}/tmp
		[ $? != 0 ] && break
		page=`expr ${page} + 200`

		cat ${tmp}/tmp | sed -e "s/^href=\"//" | sed -e "s/\/.*//" >> ${tmp}/tmp_list
	done

	if [ ! -f ${tmp}/tmp_list ]; then
		rm -fr ${tmp}
		return
	fi

	#
	# ID list will be sorted to avoid duplicate download.
	#
	sort ${tmp}/tmp_list | uniq > ${tmp}/idlist

	#
	# download Linux ML
	#
	for id in `cat ${tmp}/idlist`
	do
		n=`printf "%05d" ${num}`
		echo -n "."
		wget -q "${lore}/all/${id}/raw" -O ${dir}/${prefix}${n}

		newline=`expr ${newline} + 1`
		num=`expr ${num} + 1`

		if [ ${newline} = 80 ]; then
			newline = 00
			echo
		fi
	done

	[ ${newline} != 80 ]; echo

	rm -fr ${tmp}
}
